### ISSUE TITLE
Downgrade problems

### ISSUE THREAD

**Issue by BlackstarUA** [VladislavHromyh/UnityOptimizer#1]
I use this amazing script few week and only now notice, what it downgrade my Unity to 2.5 version.
![unity25](https://cloud.githubusercontent.com/assets/6382166/25131711/731c37dc-244f-11e7-9936-5f8e186406aa.jpg)

**Comment by VladislavHromyh** [comment]
Just uncheck checkbox named "Downgrade Unity to 2.5". It must help.

**Comment by BlackstarUA** [comment]
Thanks, It work's perfect!
